### ISSUE TITLE
have errors

### ISSUE THREAD

**Issue by kolinfluence** [Matir/sshdog#6]
```
./sshdog 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5c9a46]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc0001c2000?, {0xc0001cc000?, 0x270?, 0x24?}, 0x40?)
	<autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0x6c79c0, 0xc000164d00}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:526 +0xf5
archive/zip.(*Reader).init(0xc000150a10, {0x6c79c0?, 0xc000164d00}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:97 +0x5c
archive/zip.NewReader({0x6c79c0, 0xc000164d00}, 0x210)
	/usr/local/go/src/archive/zip/reader.go:90 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0x6c7de0?, 0xc000014048}, 0x60e369)
	/root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:128 +0x8b
github.com/daaku/go%2ezipexe.NewReader({0x6c7de0, 0xc000014048}, 0x0?)
	/root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:48 +0x98
github.com/daaku/go%2ezipexe.OpenCloser({0xc00001e6f0?, 0xc000119d10?})
	/root/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.0/zipexe.go:30 +0x57
github.com/GeertJohan/go%2erice.init.0()
	/root/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.2/appended.go:42 +0x65

```

**Comment by indiedev31** [comment]
Same error, any chance this bug will get patched? I'd love to try the tool.
